import { Redis } from "@upstash/redis";
import type { NightbotUser } from "./nightbot";
import type { RollHitResult } from "./roll-engine";
import { formatRarity, truncate } from "./format";
import { getCoreState } from "./core-system";

let redis: Redis | null = null;
function getRedis(): Redis | null {
  if (redis) return redis;
  const url = process.env.UPSTASH_REDIS_REST_URL;
  const token = process.env.UPSTASH_REDIS_REST_TOKEN;
  if (!url || !token) return null;
  redis = new Redis({ url, token });
  return redis;
}

type Branch = "archive" | "crafting" | "core" | "relic" | "scanner" | "boss" | "market" | "blueprint" | "forecast";
type Node = { id:string; branch:Branch; name:string; desc:string; cost:number; req?:string[]; core?:number; scanner?:number };
type Boss = { id:string; name:string; hp:number; maxHp:number; startedAt:number; endsAt:number; participants:Record<string,{name:string;damage:number}>; defeated:boolean };
type WorldEvent = { id:string; name:string; desc:string; rarity:"common"|"rare"|"legendary"; startedAt:number; endsAt:number; effect:string };
type Forecast = { date:string; text:string; confidence:"low"|"medium"|"high"; generatedAt:number };
type MarketItem = { id:string; name:string; cost:number; gives:string };
type ChannelState = { channelId:string; channelName:string; boss:Boss|null; worldEvent:WorldEvent|null; forecast:Forecast|null; marketDate:string|null; marketItems:MarketItem[]; stats:{bossesDefeated:number;worldEventsStarted:number;globalQuestCompletions:number}; updatedAt:number };
type RelicRarity = "common"|"uncommon"|"rare"|"epic"|"mythic"|"astral"|"glitched"|"forbidden";
type Relic = { id:string; name:string; rarity:RelicRarity; level:number; equipped:boolean };
type PlayerState = { channelId:string; userId:string; displayName:string; knowledge:number; merchantMarks:number; relicShards:number; blueprintFragments:number; scannerLevel:number; unlockedResearch:Record<string,boolean>; blueprints:Record<string,boolean>; relics:Relic[]; stats:{bossDamage:number;bossKills:number;knowledgeEarned:number;worldEventsSeen:number;relicRerolls:number}; updatedAt:number };

const PCACHE=new Map<string,{expiresAt:number;value:PlayerState}>();
const CCACHE=new Map<string,{expiresAt:number;value:ChannelState}>();
const CACHE_TTL_MS=3500;
const WORLD_EVENT_CHANCE_PER_BIOME_CHANGE=1/250;
const MIN_WORLD_EVENT_MS=25*60*1000;
function n(){return Date.now()}
function today(){return new Date().toISOString().slice(0,10)}
function pk(c:string,u:string){return `aok:player:${c}:${u}`}
function ck(c:string){return `aok:channel:${c}`}
function uid(u:NightbotUser|null){return u?.providerId??"anon"}
function uname(u:NightbotUser|null){return u?.displayName??u?.name??"Player"}
function amt(v:number){return Math.floor(v).toLocaleString("en-US")}
function clamp(v:number,min:number,max:number){return Math.max(min,Math.min(max,Math.floor(v||0)))}
function defaultPlayer(channelId:string,user:NightbotUser|null):PlayerState{return{channelId,userId:uid(user),displayName:uname(user),knowledge:0,merchantMarks:0,relicShards:0,blueprintFragments:0,scannerLevel:0,unlockedResearch:{},blueprints:{},relics:[],stats:{bossDamage:0,bossKills:0,knowledgeEarned:0,worldEventsSeen:0,relicRerolls:0},updatedAt:n()}}
function normPlayer(x:Partial<PlayerState>|null|undefined,channelId:string,user:NightbotUser|null):PlayerState{const b=defaultPlayer(channelId,user); if(!x)return b; return{...b,...x,channelId,userId:x.userId??b.userId,displayName:uname(user)||x.displayName||b.displayName,knowledge:clamp(x.knowledge??0,0,Number.MAX_SAFE_INTEGER),merchantMarks:clamp(x.merchantMarks??0,0,Number.MAX_SAFE_INTEGER),relicShards:clamp(x.relicShards??0,0,Number.MAX_SAFE_INTEGER),blueprintFragments:clamp(x.blueprintFragments??0,0,Number.MAX_SAFE_INTEGER),scannerLevel:clamp(x.scannerLevel??0,0,10),unlockedResearch:x.unlockedResearch??{},blueprints:x.blueprints??{},relics:(x.relics??[]).slice(0,50),stats:{...b.stats,...(x.stats??{})},updatedAt:n()}}
function defaultChannel(channelId:string,channelName:string):ChannelState{return{channelId,channelName,boss:null,worldEvent:null,forecast:null,marketDate:null,marketItems:[],stats:{bossesDefeated:0,worldEventsStarted:0,globalQuestCompletions:0},updatedAt:n()}}
function normChannel(x:Partial<ChannelState>|null|undefined,channelId:string,channelName:string):ChannelState{const b=defaultChannel(channelId,channelName); if(!x)return b; return{...b,...x,channelId,channelName:channelName||x.channelName||channelId,boss:x.boss??null,worldEvent:x.worldEvent??null,forecast:x.forecast??null,marketItems:x.marketItems??[],stats:{...b.stats,...(x.stats??{})},updatedAt:n()}}
async function getP(c:string,u:NightbotUser|null){const key=pk(c,uid(u)); const cached=PCACHE.get(key); if(cached&&cached.expiresAt>n())return cached.value; const r=getRedis(); if(!r)return normPlayer(null,c,u); const data=await r.get<PlayerState>(key); const st=normPlayer(data,c,u); PCACHE.set(key,{expiresAt:n()+CACHE_TTL_MS,value:st}); return st}
async function saveP(p:PlayerState){p.updatedAt=n(); PCACHE.set(pk(p.channelId,p.userId),{expiresAt:n()+CACHE_TTL_MS,value:p}); const r=getRedis(); if(r)await r.set(pk(p.channelId,p.userId),p)}
async function getC(c:string,name=c){const key=ck(c); const cached=CCACHE.get(key); if(cached&&cached.expiresAt>n())return cached.value; const r=getRedis(); if(!r)return normChannel(null,c,name); const data=await r.get<ChannelState>(key); const st=normChannel(data,c,name); CCACHE.set(key,{expiresAt:n()+CACHE_TTL_MS,value:st}); return st}
async function saveC(c:ChannelState){c.updatedAt=n(); CCACHE.set(ck(c.channelId),{expiresAt:n()+CACHE_TTL_MS,value:c}); const r=getRedis(); if(r)await r.set(ck(c.channelId),c)}
function boss(c:ChannelState){const b=c.boss; if(!b||b.defeated||b.endsAt<=n()||b.hp<=0)return null; return b}
function event(c:ChannelState){const e=c.worldEvent; if(!e||e.endsAt<=n())return null; return e}
function left(ms:number){const m=Math.floor(Math.max(0,ms)/60000); const h=Math.floor(m/60); const mm=m%60; return h>0?`${h}h ${mm}m`:`${mm}m`}

const TREE:Node[]=[
{id:"archive_memory_1",branch:"archive",name:"Archive Memory I",desc:"Knowledge foundation.",cost:30},{id:"archive_memory_2",branch:"archive",name:"Archive Memory II",desc:"Better duplicate conversion later.",cost:120,req:["archive_memory_1"]},
{id:"craft_efficiency_1",branch:"crafting",name:"Efficient Hands I",desc:"Crafting efficiency foundation.",cost:60},{id:"craft_efficiency_2",branch:"crafting",name:"Efficient Hands II",desc:"Advanced crafting support.",cost:180,req:["craft_efficiency_1"]},
{id:"core_mapping_1",branch:"core",name:"Core Mapping I",desc:"Core wall visibility foundation.",cost:75},{id:"core_mapping_2",branch:"core",name:"Core Mapping II",desc:"Better wall hints.",cost:250,req:["core_mapping_1"],core:25},
{id:"boss_damage_1",branch:"boss",name:"Hunter Training I",desc:"+10% boss damage.",cost:50},{id:"boss_damage_2",branch:"boss",name:"Hunter Training II",desc:"+25% boss damage.",cost:150,req:["boss_damage_1"]},{id:"boss_damage_3",branch:"boss",name:"Hunter Training III",desc:"+50% boss damage.",cost:400,req:["boss_damage_2"],core:25},{id:"boss_damage_4",branch:"boss",name:"Hunter Training IV",desc:"+100% boss damage.",cost:1000,req:["boss_damage_3"],core:75},{id:"boss_damage_5",branch:"boss",name:"Hunter Training V",desc:"+175% boss damage.",cost:2500,req:["boss_damage_4"],core:150},{id:"boss_damage_6",branch:"boss",name:"Hunter Training VI",desc:"+250% boss damage max.",cost:6000,req:["boss_damage_5"],core:230},
{id:"relic_slot_2",branch:"relic",name:"Relic Slot II",desc:"Unlocks second relic slot.",cost:300,core:50},{id:"relic_slot_3",branch:"relic",name:"Relic Slot III",desc:"Unlocks third relic slot.",cost:1200,req:["relic_slot_2"],core:150},{id:"relic_attune_1",branch:"relic",name:"Relic Attunement I",desc:"Relic buff foundation.",cost:500,req:["relic_slot_2"]},{id:"relic_attune_2",branch:"relic",name:"Relic Attunement II",desc:"More relic strength later.",cost:1800,req:["relic_attune_1"],core:175},{id:"relic_reforger",branch:"relic",name:"Relic Reforger",desc:"Unlocks expensive relic rarity rerolls.",cost:2500,req:["relic_attune_1"],core:200},
{id:"scanner_1",branch:"scanner",name:"Scanner I",desc:"Activity signal.",cost:40,scanner:1},{id:"scanner_2",branch:"scanner",name:"Scanner II",desc:"Boss/event summary.",cost:120,req:["scanner_1"],scanner:2,core:5},{id:"scanner_3",branch:"scanner",name:"Scanner III",desc:"Rare signal category.",cost:250,req:["scanner_2"],scanner:3,core:25},{id:"scanner_4",branch:"scanner",name:"Scanner IV",desc:"Event hints.",cost:500,req:["scanner_3"],scanner:4,core:50},{id:"scanner_5",branch:"scanner",name:"Scanner V",desc:"Best action hint.",cost:850,req:["scanner_4"],scanner:5,core:75},{id:"scanner_6",branch:"scanner",name:"Scanner VI",desc:"World event detection.",cost:1400,req:["scanner_5"],scanner:6,core:100},{id:"scanner_7",branch:"scanner",name:"Scanner VII",desc:"Forecast connection.",cost:2200,req:["scanner_6"],scanner:7,core:125},{id:"scanner_8",branch:"scanner",name:"Scanner VIII",desc:"Blueprint/scanner synergy.",cost:3200,req:["scanner_7"],scanner:8,core:150},{id:"scanner_9",branch:"scanner",name:"Scanner IX",desc:"Better website analytics.",cost:4500,req:["scanner_8"],scanner:9,core:165},{id:"scanner_10",branch:"scanner",name:"Scanner X",desc:"Max scanner, never exact guarantees.",cost:6500,req:["scanner_9"],scanner:10,core:175},
{id:"market_contacts_1",branch:"market",name:"Market Contacts I",desc:"Safer market extras.",cost:150},{id:"market_contacts_2",branch:"market",name:"Market Contacts II",desc:"Blueprint/relic offers.",cost:500,req:["market_contacts_1"]},{id:"market_haggle_1",branch:"market",name:"Market Haggle I",desc:"Small market discount later.",cost:900,req:["market_contacts_2"]},
{id:"blueprint_reading",branch:"blueprint",name:"Blueprint Reading",desc:"Reveals blueprint sources.",cost:125},{id:"blueprint_assembly",branch:"blueprint",name:"Blueprint Assembly",desc:"Fragment combining foundation.",cost:500,req:["blueprint_reading"]},{id:"wall_breaker_1",branch:"blueprint",name:"Wall Breaker I",desc:"Core-wall blueprint planning.",cost:1200,req:["blueprint_assembly"],core:100},
{id:"forecast_1",branch:"forecast",name:"Forecast I",desc:"Daily semi-smart forecast.",cost:80},{id:"forecast_2",branch:"forecast",name:"Forecast II",desc:"More activity context.",cost:300,req:["forecast_1"]},{id:"forecast_3",branch:"forecast",name:"Forecast III",desc:"More personalized forecast flavor.",cost:1000,req:["forecast_2"],core:75}
];
const BDMG:[string,number][]=[["boss_damage_1",10],["boss_damage_2",25],["boss_damage_3",50],["boss_damage_4",100],["boss_damage_5",175],["boss_damage_6",250]];
const BLUEPRINTS=[
{id:"biome_lens",name:"Biome Lens Blueprint",source:"Scanner research, rare biome events, market, boss drops",unlock:"Scanner Lv.5+ and biome components"},
{id:"relic_forge",name:"Relic Forge Blueprint",source:"Bosses, Relic Echo events, market",unlock:"Relic reroll machine"},
{id:"quantum_press",name:"Quantum Press Blueprint",source:"Core walls, Blueprint Rain, market",unlock:"Advanced component walls"},
{id:"boss_beacon",name:"Boss Beacon Blueprint",source:"Boss rewards, world events",unlock:"Special boss starts"},
{id:"archive_terminal",name:"Archive Terminal Blueprint",source:"Knowledge milestones",unlock:"High-level Knowledge upgrades"},
{id:"forbidden_frame",name:"Forbidden Frame Blueprint",source:"Core 230+, Forbidden Architect",unlock:"Late core/frame walls"}
] as const;
const RTHEMES=["Scrap","Circuit","Stardust","Archive","Hunter","Market","Blueprint","Scanner","Core","Void","Glitched","Forbidden","Solar","Lunar","Astral","Quantum","Reality","Singularity","Echo","Storm","Frost","Ember","Prism","Nebula","Dawn"] as const;
const RTYPES=["Magnet","Lens","Orb","Quill","Fang","Coin","Prism","Compass","Anvil","Shard","Crown","Engine","Beacon","Thread","Gear","Crystal","Censer","Relay","Sigil","Key"] as const;
const RR:RelicRarity[]=["common","uncommon","rare","epic","mythic","astral","glitched","forbidden"];
function catalog(){const out:{id:string;name:string}[]=[]; for(const t of RTHEMES)for(const y of RTYPES)out.push({id:`${t}_${y}`.toLowerCase(),name:`${t} ${y}`}); return out}
function bdmg(p:PlayerState){let best=0; for(const [id,pct] of BDMG)if(p.unlockedResearch[id])best=Math.max(best,pct); return best}
function hitDmg(h:RollHitResult){const r=h.effectiveRarity; const tags=(h.aura.tags??[]).map(x=>x.toLowerCase()); let d=1; if(r>=10000)d+=1; if(r>=100000)d+=3; if(r>=1000000)d+=5; if(r>=10000000)d+=10; if(r>=100000000)d+=25; if(r>=1000000000||tags.includes("challenged")||tags.includes("challenged+"))d+=50; return d}
function kFrom(r:number){if(r>=1e9)return 50; if(r>=1e8)return 25; if(r>=1e7)return 12; if(r>=1e6)return 6; if(r>=1e5)return 3; if(r>=1e4)return 1; return 0}
function pick<T>(a:readonly T[]):T{return a[Math.floor(Math.random()*a.length)]}
function makeBoss():Boss{const b=pick([{id:"scrap_titan",name:"Scrap Titan",hp:3500},{id:"circuit_hydra",name:"Circuit Hydra",hp:6500},{id:"stardust_warden",name:"Stardust Warden",hp:11000},{id:"void_leviathan",name:"Void Leviathan",hp:18000},{id:"glitched_monarch",name:"Glitched Monarch",hp:30000},{id:"forbidden_architect",name:"Forbidden Architect",hp:50000},{id:"archive_devourer",name:"Archive Devourer",hp:75000}] as const); return{id:b.id,name:b.name,hp:b.hp,maxHp:b.hp,startedAt:n(),endsAt:n()+3*60*60*1000,participants:{},defeated:false}}
function makeEvent():WorldEvent{const e=pick([{id:"meteor_shower",name:"Meteor Shower",desc:"+basic material focus.",effect:"materials",rarity:"common" as const},{id:"circuit_storm",name:"Circuit Storm",desc:"Circuit Scrap and Signal Fragment feel stronger.",effect:"circuits",rarity:"common" as const},{id:"stardust_bloom",name:"Stardust Bloom",desc:"Stardust activity is boosted.",effect:"stardust",rarity:"common" as const},{id:"archive_surge",name:"Archive Surge",desc:"Knowledge gains from rare pulls are boosted.",effect:"knowledge",rarity:"rare" as const},{id:"relic_echo",name:"Relic Echo",desc:"Relic Shards are more likely from activity rewards.",effect:"relics",rarity:"rare" as const},{id:"blueprint_rain",name:"Blueprint Rain",desc:"Blueprint Fragment rewards are more common.",effect:"blueprints",rarity:"rare" as const},{id:"market_festival",name:"Market Festival",desc:"Merchant Marks and market offers feel better.",effect:"market",rarity:"common" as const},{id:"boss_omen",name:"Boss Omen",desc:"Boss activity is favored.",effect:"boss",rarity:"rare" as const},{id:"glitched_signal",name:"Glitched Signal",desc:"Scanner rare-signal hints become sharper.",effect:"scanner",rarity:"legendary" as const},{id:"void_leak",name:"Void Leak",desc:"Rare material activity is unstable.",effect:"void",rarity:"legendary" as const}] as const); const dur=e.rarity==="legendary"?75*60000:e.rarity==="rare"?50*60000:35*60000; return{...e,startedAt:n(),endsAt:n()+Math.max(MIN_WORLD_EVENT_MS,dur)}}
function line(node:Node,p:PlayerState){const st=p.unlockedResearch[node.id]?"✅":`🧠 ${amt(node.cost)}`; const gate=node.core?` Core ${node.core}+`:""; return `${st} ${node.id}: ${node.name}${gate}`}

const RESEARCH_BRANCHES:Branch[]=["archive","crafting","core","relic","scanner","boss","market","blueprint","forecast"];
const RESEARCH_BRANCH_LABELS:Record<Branch,string>={archive:"Archive / Knowledge",crafting:"Crafting",core:"Core Walls",relic:"Relics",scanner:"Scanner",boss:"Boss Damage",market:"Marketplace",blueprint:"Blueprints",forecast:"Forecast"};
const RESEARCH_BRANCH_HELP:Record<Branch,string>={
archive:"Knowledge economy upgrades. Archive Memory means your account is learning from rare activity and duplicate systems.",
crafting:"Crafting quality-of-life and future efficiency upgrades. Kept small so crafting does not become broken.",
core:"Core-wall planning. Helps reveal walls, blueprint gates, frames, chassis, and late-core requirements.",
relic:"Relic slots, relic strength, and the expensive relic rarity reroll machine.",
scanner:"Information upgrades. More signal/detail, but never exact rare-biome guarantees.",
boss:"Boss damage upgrades. Max bonus is +250%, meaning 3.5x total damage.",
market:"Safer merchant economy. Better offers, blueprint/relic shard access, and tiny discount tools.",
blueprint:"Blueprint discovery, fragment use, and wall-breaking systems.",
forecast:"Semi-smart daily advice using recent activity, but intentionally not exact predictions."
};
function rnorm(raw:string|undefined|null){return(raw??"").toLowerCase().trim().replace(/^!+/,"").replace(/[^a-z0-9]+/g,"_").replace(/^_+|_+$/g,"")}
function findNode(raw:string){const q=rnorm(raw);return TREE.find(x=>x.id===q||rnorm(x.name)===q||rnorm(x.name).replace(/_/g,"")===q.replace(/_/g,""))}
function isBranch(raw:string):raw is Branch{return RESEARCH_BRANCHES.includes(raw as Branch)}
function effectNow(node:Node){if(node.scanner)return `Unlocks Scanner Lv.${node.scanner}.`; if(node.id.startsWith("boss_damage_")){const pct=BDMG.find(([id])=>id===node.id)?.[1]??0;return `Boss damage bonus becomes +${pct}% if this is your highest boss damage upgrade.`} if(node.id==="relic_slot_2")return"Unlocks the second relic slot."; if(node.id==="relic_slot_3")return"Unlocks the third relic slot. Balanced around Core 150+."; if(node.id==="relic_reforger")return"Unlocks the expensive relic rarity reroll machine."; if(node.id==="relic_attune_1")return"Relic effect strength foundation. Intended +5% relic effect scaling."; if(node.id==="relic_attune_2")return"Relic effect strength foundation. Intended +10% relic effect scaling."; if(node.id==="archive_memory_1")return"Archive/Knowledge foundation. Your activity becomes easier to convert into Knowledge rewards later."; if(node.id==="archive_memory_2")return"Deeper Archive memory. Improves duplicate blueprint/relic conversion into Knowledge later."; if(node.id==="forecast_1")return"Unlocks/justifies basic daily forecast usage."; if(node.id==="forecast_2")return"Forecast starts caring more about activity context."; if(node.id==="forecast_3")return"Forecast becomes more personalized once later systems use player progress."; if(node.branch==="blueprint")return"Blueprint wall/planning upgrade. Used to reveal or prepare late unlock requirements."; if(node.branch==="core")return"Core wall planning upgrade. Used for future wall visibility and recipe planning."; if(node.branch==="market")return"Marketplace upgrade foundation. Used for safer offers and later market improvements."; if(node.branch==="crafting")return"Crafting efficiency foundation. Kept small to protect balance."; return"Progression foundation upgrade."}
function whyNode(node:Node){if(node.branch==="archive")return"This branch answers: how do I earn/use Knowledge better?"; if(node.branch==="crafting")return"This branch answers: how do I craft smoother without making materials worthless?"; if(node.branch==="core")return"This branch answers: what wall is coming and what blueprint/frame/chassis do I need?"; if(node.branch==="relic")return"This branch answers: how many relics can I use and how far can relic rarity go?"; if(node.branch==="scanner")return"This branch answers: what is happening now, and what should I focus on?"; if(node.branch==="boss")return"This branch answers: how hard do my rolls hit bosses?"; if(node.branch==="market")return"This branch answers: what safe items can I buy without breaking the economy?"; if(node.branch==="blueprint")return"This branch answers: how do I unlock walls, machines, and special recipes?"; return"This branch answers: what is a good direction today without exact spoilers?"}
function reqText(node:Node){return[(node.req?.length?`Requires: ${node.req.join(", ")}`:null),(node.core?`Core ${node.core}+`:null),`Cost: ${amt(node.cost)} Knowledge`].filter(Boolean).join(" | ")}
function fmtBranches(){return truncate(`🧠 Research Branches: ${RESEARCH_BRANCHES.map(b=>`${b}=${RESEARCH_BRANCH_LABELS[b]}`).join(" | ")} | Use !research <branch>, !research info <id>, or !research unlock <id>`,390)}
function fmtBranch(branch:Branch,p:PlayerState,rawPage?:string){const nodes=TREE.filter(x=>x.branch===branch); const total=Math.max(1,Math.ceil(nodes.length/4)); const page=Math.max(1,Math.min(total,Number(rawPage||1)||1)); const shown=nodes.slice((page-1)*4,page*4).map(x=>line(x,p)); return truncate(`🧠 ${RESEARCH_BRANCH_LABELS[branch]} ${page}/${total}: ${RESEARCH_BRANCH_HELP[branch]} | ${shown.join(" | ")}`,390)}
function fmtNode(node:Node,p:PlayerState,rawPage?:string){const page=Math.max(1,Math.min(2,Number(rawPage||1)||1)); const unlocked=p.unlockedResearch[node.id]?"Unlocked ✅":"Locked ⬜"; if(page===2)return truncate(`🧠 ${node.name} 2/2 | Why: ${whyNode(node)} | Branch: ${RESEARCH_BRANCH_LABELS[node.branch]} | ID: ${node.id} | Unlock: !research unlock ${node.id}`,390); return truncate(`🧠 ${node.name} 1/2 | ${unlocked} | ${reqText(node)} | Effect: ${effectNow(node)} | Page 2: !research info ${node.id} 2`,390)}

export async function formatKnowledge(channelId:string,user:NightbotUser|null){const p=await getP(channelId,user); const un=Object.values(p.unlockedResearch).filter(Boolean).length; return truncate(`🧠 ${p.displayName} | Knowledge: ${amt(p.knowledge)} | Research: ${un}/${TREE.length} | Scanner Lv.${p.scannerLevel}/10 | Merchant Marks: ${amt(p.merchantMarks)} | Relic Shards: ${amt(p.relicShards)}`)}
export async function formatResearch(channelId:string,user:NightbotUser|null,raw=""){const p=await getP(channelId,user); const parts=raw.trim().split(/\s+/).filter(Boolean); const mode=rnorm(parts[0]??""); if(!mode||mode==="help")return truncate(`🧠 Research | Knowledge ${amt(p.knowledge)} | Use !research branches, !research <branch>, !research info <id>, !research unlock <id>. Example: !research boss`,390); if(mode==="branches"||mode==="tree")return fmtBranches(); if(mode==="info"||mode==="detail"||mode==="details"){const rawNode=parts.slice(1).filter(x=>!/^[12]$/.test(x)).join(" "); const node=findNode(rawNode); if(!node)return "Unknown research upgrade. Use !research branches or !research <branch>."; return fmtNode(node,p,parts[parts.length-1])} if(isBranch(mode))return fmtBranch(mode,p,parts[1]); const direct=findNode(parts[0]); if(direct)return fmtNode(direct,p,parts[1]); const page=clamp(Number(parts[0]||1),1,99); const size=5,total=Math.max(1,Math.ceil(TREE.length/size)),safe=Math.min(page,total); const shown=TREE.slice((safe-1)*size,safe*size).map(x=>line(x,p)); return truncate(`🧠 Research All ${safe}/${total} | Knowledge ${amt(p.knowledge)} | ${shown.join(" | ")} | Details: !research info <id>`,390)}
export async function unlockResearch(channelId:string,user:NightbotUser|null,rawId:string){const id=rawId.trim().toLowerCase(); const node=TREE.find(x=>x.id===id); if(!node)return "Unknown research. Use !research branches or !research info <id>."; const p=await getP(channelId,user); if(p.unlockedResearch[id])return `${node.name} is already unlocked.`; for(const req of node.req??[])if(!p.unlockedResearch[req])return `${node.name} requires ${req} first.`; if(node.core){const core=await getCoreState(channelId,user); if(core.coreTier<node.core)return `${node.name} requires Core ${node.core}. Current Core: ${core.coreTier}.`} if(p.knowledge<node.cost)return `${node.name} needs ${amt(node.cost)} Knowledge. You have ${amt(p.knowledge)}.`; p.knowledge-=node.cost; p.unlockedResearch[id]=true; if(node.scanner)p.scannerLevel=Math.max(p.scannerLevel,node.scanner); await saveP(p); return `✅ Unlocked ${node.name}! ${node.desc}`}
export async function formatScanner(channelId:string,channelName:string,user:NightbotUser|null){const p=await getP(channelId,user); const c=await getC(channelId,channelName); const e=event(c),b=boss(c); const signal=p.scannerLevel>=3?(e?.rarity==="legendary"?"High":e?.rarity==="rare"?"Medium":"Low"):"Locked"; const parts=[`📡 Scanner Lv.${p.scannerLevel}/10`,`Rare Signal: ${signal}`]; if(p.scannerLevel>=2)parts.push(`Boss: ${b?`${b.name} ${amt(b.hp)}/${amt(b.maxHp)} HP`:"None"}`); if(p.scannerLevel>=4)parts.push(`Event: ${e?`${e.name} ${left(e.endsAt-n())}`:"None"}`); if(p.scannerLevel>=5)parts.push(`Best action: ${e?.effect==="knowledge"?"hunt 1/10k+ auras for Knowledge":b?"roll to damage boss":"build Knowledge"}`); return truncate(parts.join(" | "))}
export async function formatWorldEvent(channelId:string,channelName:string){const c=await getC(channelId,channelName); const e=event(c); if(!e)return `🌍 No Activity world event. 1/250 chance on biome change, 25m minimum.`; return truncate(`🌍 ${e.name} (${e.rarity}) | ${e.desc} | Left: ${left(e.endsAt-n())}`)}
export async function maybeStartActivityWorldEvent(o:{channelId:string;channelName:string;biomeId:string}){if(Math.random()>=WORLD_EVENT_CHANCE_PER_BIOME_CHANGE)return{started:false,message:null as string|null}; const c=await getC(o.channelId,o.channelName); if(event(c))return{started:false,message:null as string|null}; const e=makeEvent(); c.worldEvent=e; c.stats.worldEventsStarted+=1; await saveC(c); return{started:true,message:`🌍 Activity Of Knowledge World Event: ${e.name} started for ${left(e.endsAt-e.startedAt)}! ${e.desc}`}}
export async function formatForecast(channelId:string,channelName:string,user?:NightbotUser|null){const c=await getC(channelId,channelName); const date=today(); if(c.forecast?.date===date)return truncate(c.forecast.text); const e=event(c),b=boss(c); const focus=e?.effect==="knowledge"?"Knowledge":pick(["Knowledge","Blueprint Fragments","Relic Shards","Merchant Marks","Scanner upgrades","Core walls"] as const); const conf:Forecast["confidence"]=b||e?"medium":"low"; const tip=b?`Boss activity is live: ${b.name}. Rolling contributes damage.`:e?`${e.name} is active, so ${focus} looks interesting.`:`Signals are calm. Focus ${focus}, quests, and steady rolls.`; c.forecast={date,confidence:conf,generatedAt:n(),text:`🔮 Forecast (${conf}): Focus: ${focus}. ${tip} Not exact — just an activity read.`}; await saveC(c); return truncate(c.forecast.text)}
export async function formatBoss(channelId:string,channelName:string){const c=await getC(channelId,channelName); const b=c.boss; if(!b)return `🐉 No boss active. Mods can use !boss start.`; if(b.defeated||b.hp<=0)return `🏆 ${b.name} was defeated! Use !boss start for a new boss.`; const top=Object.values(b.participants).sort((a,b)=>b.damage-a.damage).slice(0,3).map(p=>`${p.name} ${amt(p.damage)}`).join(", "); return truncate(`🐉 ${b.name} | HP ${amt(Math.max(0,b.hp))}/${amt(b.maxHp)} | Left ${left(b.endsAt-n())} | Top: ${top||"none yet"}`)}
export async function startBoss(channelId:string,channelName:string){const c=await getC(channelId,channelName); const cur=boss(c); if(cur)return `${cur.name} is already active. HP ${amt(cur.hp)}/${amt(cur.maxHp)}.`; c.boss=makeBoss(); await saveC(c); return `🐉 Boss started: ${c.boss.name}! HP ${amt(c.boss.maxHp)} | Rolls now deal boss damage.`}
export async function recordActivityRolls(o:{channelId:string;channelName:string;user:NightbotUser|null;results:RollHitResult[]}){if(!o.user||o.results.length===0)return; const best=Math.max(...o.results.map(r=>r.effectiveRarity)); const kg=kFrom(best); const c=await getC(o.channelId,o.channelName); const b=boss(c),e=event(c); if(!b&&!e&&kg<=0)return; const p=await getP(o.channelId,o.user); let sp=false, sc=false; if(kg>0){const gain=Math.max(1,Math.floor(kg*(e?.effect==="knowledge"?1.25:1))); p.knowledge+=gain; p.stats.knowledgeEarned+=gain; sp=true} if(e&&p.stats.worldEventsSeen===0){p.stats.worldEventsSeen+=1; sp=true} if(b){const base=o.results.reduce((s,r)=>s+hitDmg(r),0); const dmg=Math.max(1,Math.floor(base*(1+bdmg(p)/100))); b.hp=Math.max(0,b.hp-dmg); const ent=b.participants[p.userId]??{name:p.displayName,damage:0}; ent.name=p.displayName; ent.damage+=dmg; b.participants[p.userId]=ent; p.stats.bossDamage+=dmg; p.merchantMarks+=Math.max(1,Math.floor(dmg/25)); sp=true; sc=true; if(b.hp<=0&&!b.defeated){b.defeated=true; c.stats.bossesDefeated+=1; p.stats.bossKills+=1; p.knowledge+=100; p.relicShards+=5; p.blueprintFragments+=2}} if(sp)await saveP(p); if(sc)await saveC(c)}
function marketItems(date:string):MarketItem[]{const seed=date.split("").reduce((s,ch)=>s+ch.charCodeAt(0),0); return[{id:"scrap_pack",name:"Scrap Pack",cost:8,gives:"basic materials"},{id:"circuit_pack",name:"Circuit Pack",cost:20,gives:"Circuit Scrap + Signal Fragments"},{id:"knowledge_note",name:"Knowledge Note",cost:35,gives:"Knowledge"},{id:"relic_shards",name:"Relic Shards",cost:50,gives:"Relic Shards"},{id:"blueprint_fragment",name:"Blueprint Fragment",cost:60,gives:"Blueprint Fragment"},{id:"boss_beacon",name:"Boss Beacon",cost:120,gives:"boss-start material later"}].map((x,i)=>({...x,cost:x.cost+((seed+i*7)%9)})).slice(0,5)}
export async function formatMarket(channelId:string,channelName:string){const c=await getC(channelId,channelName),date=today(); if(c.marketDate!==date||c.marketItems.length===0){c.marketDate=date;c.marketItems=marketItems(date);await saveC(c)} return truncate(`🏪 Activity Market | ${c.marketItems.map(x=>`${x.id} ${x.cost} Marks`).join(" | ")} | Use !market buy <id>`)}
export async function buyMarketItem(channelId:string,channelName:string,user:NightbotUser|null,itemId:string){const c=await getC(channelId,channelName),date=today(); if(c.marketDate!==date||c.marketItems.length===0){c.marketDate=date;c.marketItems=marketItems(date);await saveC(c)} const item=c.marketItems.find(x=>x.id===itemId.trim().toLowerCase()); if(!item)return "Unknown market item. Use !market."; const p=await getP(channelId,user); if(p.merchantMarks<item.cost)return `${item.name} costs ${item.cost} Merchant Marks. You have ${amt(p.merchantMarks)}.`; p.merchantMarks-=item.cost; if(item.id==="knowledge_note")p.knowledge+=25; else if(item.id==="relic_shards")p.relicShards+=5; else if(item.id==="blueprint_fragment")p.blueprintFragments+=1; else p.knowledge+=5; await saveP(p); return `✅ Bought ${item.name}. Gained ${item.gives}.`}
export async function formatBlueprints(channelId:string,user:NightbotUser|null,raw=""){const p=await getP(channelId,user); const q=raw.trim().toLowerCase(); if(q){const bp=BLUEPRINTS.find(x=>x.id===q||x.name.toLowerCase().includes(q)); if(!bp)return "Unknown blueprint. Use !blueprints."; return truncate(`📘 ${bp.name}: unlocks ${bp.unlock}. Sources: ${bp.source}. Owned: ${p.blueprints[bp.id]?"yes":"no"}`)} return truncate(`📘 Blueprints | Fragments: ${amt(p.blueprintFragments)} | ${BLUEPRINTS.map(bp=>`${p.blueprints[bp.id]?"✅":"⬜"} ${bp.id}`).join(" | ")} | !blueprints <id>`)}
export async function formatRelics(channelId:string,user:NightbotUser|null){const p=await getP(channelId,user); const owned=p.relics.length?p.relics.slice(0,4).map(r=>`${r.equipped?"⭐":""}${r.name} ${r.rarity} Lv.${r.level}`).join(" | "):"No relics yet. Bosses/market/events can give shards and relic access."; return truncate(`🧿 Relics | Catalog: ${catalog().length} | Owned: ${p.relics.length} | Shards: ${amt(p.relicShards)} | ${owned}`)}
function nextR(r:RelicRarity):RelicRarity{const i=RR.indexOf(r),roll=Math.random(); let x=i; if(roll<.01)x+=2; else if(roll<.26)x+=1; else if(roll>.90)x-=1; return RR[clamp(x,0,RR.length-1)]}
export async function rerollRelic(channelId:string,user:NightbotUser|null,raw=""){const p=await getP(channelId,user); if(!p.unlockedResearch.relic_reforger)return "Relic reroll machine requires Relic Reforger research."; const wanted=raw.trim().toLowerCase(); const relic=p.relics.find(r=>r.id===wanted||r.name.toLowerCase()===wanted); if(!relic)return "Relic not found. Use !relics."; const idx=RR.indexOf(relic.rarity),shards=50+idx*150,know=500+idx*1000; if(p.relicShards<shards||p.knowledge<know)return `Reroll ${relic.name} costs ${amt(shards)} Relic Shards + ${amt(know)} Knowledge.`; const old=relic.rarity; p.relicShards-=shards; p.knowledge-=know; relic.rarity=nextR(relic.rarity); p.stats.relicRerolls+=1; await saveP(p); return `🧿 Rerolled ${relic.name}: ${old} → ${relic.rarity}.`}
